# Generated by Django 4.2.4 on 2023-08-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='НАЗВАНИЕ')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='НАЗВАНИЕ')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИМЯ')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиента',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('inn', models.CharField(max_length=255, null=True, verbose_name='Инн')),
                ('is_physic', models.BooleanField(null=True, verbose_name='Физ. лицо?')),
                ('is_base', models.BooleanField(null=True, verbose_name='Базовый ?')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='КОММЕНТАРИЙ')),
            ],
            options={
                'verbose_name': 'Плательщики',
                'verbose_name_plural': 'Плательщики',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('flat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Офис/квартира')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Плательщики',
                'verbose_name_plural': 'Плательщики',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='НАЗВАНИЕ')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(null=True, verbose_name='Выполнена?')),
                ('by_shedule', models.BooleanField(null=True, verbose_name='Расписание ?')),
                ('priority', models.BooleanField(null=True, verbose_name='Расписание ?')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='client.client')),
            ],
            options={
                'verbose_name': 'Заметки',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
