# Generated by Django 4.2.4 on 2023-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='invite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приглашение'),
        ),
    ]
