# Generated by Django 4.2.4 on 2023-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_contact_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='old_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город в старой базе'),
        ),
    ]
