# Generated by Django 4.2.4 on 2023-08-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_note_note_old_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адрес доставки'},
        ),
    ]
