# Generated by Django 4.2.4 on 2023-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_category_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-id',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.BooleanField(null=True, verbose_name='Приоритет ?'),
        ),
    ]
