# Generated by Django 4.2.4 on 2023-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_note_created_at_alter_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
