# Generated by Django 4.2.4 on 2023-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_filter_remove_product_subcategory_product_isdiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isDiscount',
            field=models.BooleanField(default=True, verbose_name='Товар со скидкой?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='Товар новинка?'),
        ),
    ]
