# Generated by Django 4.2.4 on 2023-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discount_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ('product',), 'verbose_name': 'Цена/Вес товара', 'verbose_name_plural': 'Цены/Веса товаров'},
        ),
        migrations.AddField(
            model_name='productprice',
            name='at_store',
            field=models.IntegerField(default=0, null=True, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='textLabel',
            field=models.CharField(max_length=20, null=True, verbose_name='Фасовка'),
        ),
    ]
