# Generated by Django 4.2.4 on 2023-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productprice_options_productprice_at_store_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True, verbose_name='Объем, m3'),
        ),
    ]
