# Generated by Django 4.2.4 on 2023-10-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_feedback_remove_product_description_producttab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedingRate',
        ),
    ]
