# Generated by Django 4.2.4 on 2023-10-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_delivery_remove_product_feedingrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tour',
        ),
    ]
