# Generated by Django 4.2.4 on 2023-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
