# Generated by Django 4.2.4 on 2023-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('timezone', models.CharField(max_length=255, null=True, verbose_name='Зона')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='Страна')),
                ('post_index', models.CharField(max_length=255, null=True, verbose_name='Индекс')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Регион')),
                ('area', models.CharField(max_length=255, null=True, verbose_name='Область')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Тип')),
                ('latitude', models.CharField(max_length=255, null=True, verbose_name='Широта')),
                ('longtitude', models.CharField(max_length=255, null=True, verbose_name='Долгота')),
            ],
        ),
    ]
