# Generated by Django 4.2.4 on 2023-09-14 14:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_blogcategory_blogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[740, 475], upload_to='blog')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка,')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[740, 475], upload_to='blog')),
                ('orange_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='текст рыжий,')),
                ('black_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='текст черный,')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка,')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='текст на кнопке,')),
            ],
            options={
                'verbose_name': 'Баннер на главной',
                'verbose_name_plural': 'Баннер на главной',
            },
        ),
        migrations.AlterModelOptions(
            name='blogitem',
            options={'ordering': ('-id',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='readTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время прочтения'),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
