# Generated by Django 4.2.4 on 2023-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
