# Generated by Django 4.2.4 on 2023-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
