# Generated by Django 4.2.4 on 2023-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
