# Generated by Django 4.2.4 on 2023-09-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_status_rename_user_order_manager_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userName',
        ),
    ]
