# Generated by Django 4.2.4 on 2023-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_totalprice_remove_orderitem_totalprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
