# Generated by Django 4.2.4 on 2023-10-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_deliverystatus_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
