# Generated by Django 4.2.4 on 2023-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
