# Generated by Django 4.2.4 on 2023-10-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_delivery_description_delivery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='login',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='ССылка на сервер оплаты'),
        ),
    ]
