# Generated by Django 4.2.4 on 2023-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_paymenttype_login_paymenttype_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
