# Generated by Django 4.2.4 on 2023-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_paymenttype_login_alter_paymenttype_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ССылка на сервер оплаты'),
        ),
    ]
