# Generated by Django 4.2.4 on 2023-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_paymenttype_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
