# Generated by Django 4.2.4 on 2023-10-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
