# Generated by Django 4.2.4 on 2023-10-25 17:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
