# Generated by Django 4.2.4 on 2023-10-25 17:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_status_bg_color_status_is_default_status_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeliveryCompany',
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
    ]
