# Generated by Django 4.2.4 on 2023-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_orderitem_price_changed_orderitem_price_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pay_done',
            field=models.BooleanField(default=False),
        ),
    ]
